/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.ChannelCatalog;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.MarketCatalog;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductCatalog;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageSuppliersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;
    Market selectedmarket;

    public ManageSuppliersJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        initializeTable();

    }

    public void initializeTable() {

//clear supplier table
        //SuppliersComboBox.removeAllItems();
        MarketsComboBox.removeAllItems();

        int rc = MktChannelCatalogTable.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) MktChannelCatalogTable.getModel()).removeRow(i);
        }
//load suppliers to the combobox

        //ArrayList<Supplier> supplierlist = business.getSupplierDirectory().getSuplierList();
        ArrayList<Market> markets = business.getMarketCatalog().getMarkets();
        
        if (markets.isEmpty()) {
            return;
        }
        for (Market m : markets) {
            MarketsComboBox.addItem(m.getName());
            MarketsComboBox.setSelectedIndex(0);

            //String suppliername = (String) MarketsComboBox.getSelectedItem();
            //String marketname = (String) MarketsComboBox.getSelectedItem();

            //selectedsupplier = business.getSupplierDirectory().findSupplier(suppliername);
            //selectedmarket = business.getName();

            //ProductCatalog pc = selectedsupplier.getProductCatalog();
            //MarketCatalog mc = selectedmarket.getMarkets();

//            for (Product pt : pc.getProductList()) {
//
//                Object[] row = new Object[5];
//                row[0] = pt;
//                row[1] = pt.getFloorPrice();
//                row[2] = pt.getCeilingPrice();
//                row[3] = pt.getTargetPrice();
////                row[1] = pt.getPerformanceMeasure();
////               row[2] = la.getName();
//                ((DefaultTableModel) MktChannelCatalogTable.getModel()).addRow(row);
//            }

        }
    }

    public void refreshTable() {

//clear supplier table
        int rc = MktChannelCatalogTable.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) MktChannelCatalogTable.getModel()).removeRow(i);
        }

        String suppliername = (String) MarketsComboBox.getSelectedItem();

        selectedsupplier = business.getSupplierDirectory().findSupplier(suppliername);
        if (selectedsupplier == null) {
            return;
        }
        ProductCatalog pc = selectedsupplier.getProductCatalog();

        for (Product pt : pc.getProductList()) {

            Object[] row = new Object[5];
            row[0] = pt;
            row[1] = pt.getFloorPrice();
            row[2] = pt.getCeilingPrice();
            row[3] = pt.getTargetPrice();
//                row[1] = pt.getPerformanceMeasure();
//               row[2] = la.getName();
            ((DefaultTableModel) MktChannelCatalogTable.getModel()).addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarketsComboBox = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        MktChannelCatalogTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MarketsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarketsComboBoxActionPerformed(evt);
            }
        });
        add(MarketsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        Next.setText("Next >>");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 80, -1));

        jLabel1.setText("Markets");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        MktChannelCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Channel Type"
            }
        ));
        MktChannelCatalogTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MktChannelCatalogTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MktChannelCatalogTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(MktChannelCatalogTable);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 580, 100));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Market Channel Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 550, -1));

        jLabel8.setText("Channels");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        ManageProductPerformanceDetail mppd = new ManageProductPerformanceDetail(selectedproduct, CardSequencePanel);
        CardSequencePanel.add(mppd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_NextActionPerformed

    private void MarketsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarketsComboBoxActionPerformed
        // TODO add your handling code here:

        refreshTable();
        //String sname = (String) SuppliersComboBox.getSelectedItem();
        //selectedsupplier = business.getSupplierDirectory().findSupplier(sname);


    }//GEN-LAST:event_MarketsComboBoxActionPerformed

    private void MktChannelCatalogTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MktChannelCatalogTableMousePressed
        // TODO add your handling code here:
        int suppliertablesize = MktChannelCatalogTable.getRowCount();
        int selectedrow = MktChannelCatalogTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > suppliertablesize - 1) {
            return;
        }
        selectedproduct = (Product) MktChannelCatalogTable.getValueAt(selectedrow, 0);
        if (selectedproduct == null) {
            return;
        }
        
        ProductSummary productsummary = new ProductSummary(selectedproduct);

//        productNameTextField.setText(selectedproduct.toString());
//        String revenues = String.valueOf(productsummary.getSalesRevenues());
//        productRevenueTextField.setText(revenues);
//        productFrequencyAboveTargetTextField.setText( String.valueOf(productsummary.getNumberAboveTarget()));
//        productFrequencyBelowTargetTextField.setText( String.valueOf(productsummary.getNumberBelowTarget()));
//        productPricePerformanceTextField.setText(String.valueOf(productsummary.getProductPricePerformance()));
    }//GEN-LAST:event_MktChannelCatalogTableMousePressed

    private void MktChannelCatalogTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MktChannelCatalogTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MktChannelCatalogTableMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String marketname = (String) MarketsComboBox.getSelectedItem();
        Market m = business.getMarketCatalog().findMarket(marketname);
      //  selectedmarket = business.getName();

            //ProductCatalog pc = selectedsupplier.getProductCatalog();
            //MarketCatalog mc = selectedmarket.getMarkets();

            for (Channel c : m.getValidchannels()) {
                Object[] row = new Object[1];
                row[0] = c.getChannelType();
               ((DefaultTableModel) MktChannelCatalogTable.getModel()).addRow(row);
           }
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> MarketsComboBox;
    private javax.swing.JTable MktChannelCatalogTable;
    private javax.swing.JButton Next;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
